openapi: 3.0.3
info:
  title: ArmadaAPI
  version: '0.1'
  x-logo:
    url: ''
  description: Draft definition of an API supporting Star Wars Armada fleet building.
  contact:
    name: Craig Fleming
    url: 'https://github.com'
    email: rythos42@gmail.com
paths:
  /squadrons:
    get:
      summary: Your GET endpoint
      tags:
        - squadron
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Squadron'
      operationId: get-squadrons
      description: Return a list of all squadrons.
  /ships:
    get:
      summary: Your GET endpoint
      tags:
        - ship
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ship'
      operationId: get-ships
      description: Return a list of all ships.
  /upgrades:
    get:
      summary: Your GET endpoint
      tags:
        - upgrade
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upgrade'
      operationId: get-upgrades
      description: Return a list of all upgrades.
components:
  securitySchemes: {}
  schemas:
    Faction:
      description: ''
      type: object
      x-examples:
        example:
          name: Republic
          id: republic
      properties:
        name:
          type: string
          minLength: 1
        id:
          type: string
          minLength: 1
      required:
        - name
        - id
    DefenseToken:
      description: ''
      x-examples:
        example: Brace
      type: object
      properties:
        name:
          type: string
        id:
          $ref: '#/components/schemas/DefenseTokenId'
    DiceId:
      type: string
      title: DiceId
      enum:
        - red
        - blue
        - black
    Ship:
      title: Ship
      type: object
      description: ''
      properties:
        id:
          type: string
        name:
          type: string
        hull:
          type: integer
        flak:
          $ref: '#/components/schemas/PrintedDicePool'
        defenseTokens:
          $ref: '#/components/schemas/PrintedDefenseTokenSuite'
        command:
          type: integer
        squadron:
          type: integer
        engineering:
          type: integer
        frontArc:
          $ref: '#/components/schemas/PrintedDicePool'
        leftArc:
          $ref: '#/components/schemas/PrintedDicePool'
        rightArc:
          $ref: '#/components/schemas/PrintedDicePool'
        rearArc:
          $ref: '#/components/schemas/PrintedDicePool'
        yawChart:
          $ref: '#/components/schemas/YawChart'
        traits:
          type: array
          items:
            $ref: '#/components/schemas/Trait'
        points:
          type: integer
        upgradeIcons:
          type: array
          items:
            $ref: '#/components/schemas/UpgradeIcon'
        faction:
          $ref: '#/components/schemas/Faction'
    PrintedDicePool:
      title: PrintedDicePool
      type: array
      items:
        $ref: '#/components/schemas/Dice'
    PrintedDefenseTokenSuite:
      title: PrintedDefenseTokenSuite
      type: array
      items:
        $ref: '#/components/schemas/DefenseToken'
    Yaw:
      type: integer
      title: Yaw
      minimum: 0
      maximum: 2
    YawAtSpeed:
      title: YawAtSpeed
      type: array
      items:
        $ref: '#/components/schemas/Yaw'
    YawChart:
      title: YawChart
      type: array
      items:
        $ref: '#/components/schemas/YawAtSpeed'
    Trait:
      title: Trait
      type: string
    UpgradeIconId:
      type: string
      title: UpgradeIconId
      enum:
        - commander
        - defensive-retrofit
        - experimental-retrofit
        - fleet-command
        - fleet-support
        - ion-cannon
        - offensive-retrofit
        - officer
        - ordnance
        - superweapon
        - support-team
        - title
        - turblolaser
        - weapons-team
    Squadron:
      title: Squadron
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        speed:
          type: integer
        hull:
          type: integer
        antiShip:
          $ref: '#/components/schemas/PrintedDicePool'
        antiSquadron:
          $ref: '#/components/schemas/PrintedDicePool'
        specialAbility:
          type: string
        keywords:
          type: array
          items:
            $ref: '#/components/schemas/PrintedKeyword'
    Keyword:
      title: Keyword
      type: object
      x-examples:
        example:
          id: escort
          name: Escort
      properties:
        name:
          type: string
        id:
          $ref: '#/components/schemas/KeywordId'
        ruleText:
          type: string
    PrintedKeyword:
      title: PrintedKeyword
      type: object
      properties:
        keyword:
          $ref: '#/components/schemas/Keyword'
        value:
          type: integer
    KeywordId:
      type: string
      title: KeywordId
      enum:
        - adept
        - ai
        - assault
        - bomber
        - cloak
        - counter
        - dodge
        - escort
        - grit
        - heavy
        - intel
        - relay
        - rogue
        - scout
        - screen
        - snipe
        - strategic
        - swarm
    DefenseTokenId:
      type: string
      title: DefenseTokenId
      enum:
        - brace
        - contain
        - evade
        - redirect
        - salvo
        - scatter
    Dice:
      title: Dice
      type: object
      properties:
        id:
          $ref: '#/components/schemas/DiceId'
        name:
          type: string
    UpgradeIcon:
      title: UpgradeIcon
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UpgradeIconId'
        name:
          type: string
    Upgrade:
      title: Upgrade
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        cardText:
          type: string
        cost:
          type: integer
        upgradeIcons:
          type:
            - array
          items:
            $ref: '#/components/schemas/UpgradeIcon'
        isRecurring:
          type: boolean
        startingResources:
          type: array
          items:
            $ref: '#/components/schemas/Command'
        recurranceCost:
          type: array
          items:
            $ref: '#/components/schemas/CommandId'
    CommandId:
      type: string
      title: CommandId
      enum:
        - concentrate-fire
        - navigate
        - repair
        - squadron
        - any
    Command:
      title: Command
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CommandId'
        name:
          type: string
  headers: {}
  responses: {}
  parameters: {}
servers:
  - url: 'https://api.example.io'
    description: Craig Fleming
security: []
tags:
  - name: faction
  - name: ship
  - name: squadron
  - name: upgrade
