openapi: 3.0.3
info:
  title: ArmadaAPI
  version: '0.1'
  x-logo:
    url: ''
  description: Draft definition of an API supporting Star Wars Armada fleet building.
  contact:
    name: Craig Fleming
    url: 'https://github.com'
    email: rythos42@gmail.com
paths:
  /factions:
    summary: Factions
    description: Resource related to factions.
    get:
      tags:
        - faction
      operationId: get_factions
      summary: Return a list of factions.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                x-examples:
                  example-1:
                    - name: Republic
                      identifier: republic
                    - name: Rebel
                      identifier: rebel
                    - name: Empire
                      identifier: empire
                    - name: Separatist
                      identifier: separatist
                items:
                  $ref: '#/components/schemas/Faction'
              examples:
                example-1:
                  value:
                    - name: Republic
                      identifier: republic
                    - name: Rebel
                      identifier: rebel
                    - name: Empire
                      identifier: empire
                    - name: Separatist
                      identifier: separatist
      description: Return a list of factions.
    x-last-modified: 1620443464394
  '/factions/{factionIdentifier}/ships':
    parameters:
      - schema:
          type: string
        name: factionIdentifier
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - faction
        - ship
      responses:
        '200':
          description: OK
      operationId: get-factions-factionIdentifier-ships
      description: Return a list of ships that belong to the given faction.
  '/factions/{factionIdentifier/squadrons':
    get:
      summary: Your GET endpoint
      tags:
        - squadron
        - faction
      responses:
        '200':
          description: OK
      operationId: get-factions-factionIdentifier-squadrons
      description: Return a list of squadrons that belong to the given faction.
  '/factions/{factionIdentifier}/upgrades':
    parameters:
      - schema:
          type: string
        name: factionIdentifier
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - upgrade
        - faction
      responses:
        '200':
          description: OK
      operationId: get-factions-factionIdentifier-upgrades
      description: Return a list of upgrades that belong _only_ to the given faction.
  /squadrons:
    get:
      summary: Your GET endpoint
      tags:
        - squadron
      responses:
        '200':
          description: OK
      operationId: get-squadrons
      description: Return a list of all squadrons.
  /ships:
    get:
      summary: Your GET endpoint
      tags:
        - ship
      responses:
        '200':
          description: OK
      operationId: get-ships
      description: Return a list of all ships.
  /upgrades:
    get:
      summary: Your GET endpoint
      tags:
        - upgrade
      responses:
        '200':
          description: OK
      operationId: get-upgrades
      description: Return a list of all upgrades.
components:
  securitySchemes: {}
  schemas:
    Faction:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        identifier:
          type: string
          minLength: 1
      required:
        - name
        - identifier
      x-examples:
        example-1:
          name: Republic
          identifier: republic
  headers: {}
  responses: {}
  parameters: {}
servers:
  - url: 'https://api.example.io'
    description: Craig Fleming
security: []
tags:
  - name: faction
  - name: ship
  - name: squadron
  - name: upgrade
